In [21]:
import pandas as pd

In [22]:
df=pd.read_csv('character_stats.csv')

In [23]:
df.head()

,character_name,character_class,ocid,date,remain_ap,최소 스탯공격력,최대 스탯공격력,데미지,보스 몬스터 데미지,최종 데미지,...,재사용 대기시간 감소 (%),재사용 대기시간 미적용,속성 내성 무시,상태이상 추가 데미지,무기 숙련도,추가 경험치 획득,공격력,마력,전투력,소환수 지속시간 증가
0,Baddy,메카닉,1cf1d6efc0b9b32c9fdc241b2abfcedd,NaN,0,153868860,181022186,117.00,433.0,56.20,...,6,0,5.0,14.0,85,271.0,9282,2238,483009339,20
1,BrutalThief,섀도어,c288966edfe3e400173aec2853c89c24,NaN,0,94223427,104692695,105.50,281.0,72.46,...,6,7,5.0,6.0,90,313.0,7841,1956,177511333,0
2,Chaos,키네시스,3a84007dd5dbe02c65a731da2304372a,NaN,0,104335257,112188445,106.00,293.0,173.09,...,6,15,5.0,9.0,93,389.0,1959,6728,145531692,0
3,Lacheln,은월,af471d7a62303f2359f274a74296ce8aefe8d04e6d233b...,NaN,0,253387095,281541213,183.00,289.0,104.16,...,6,7,5.0,9.0,90,376.0,9535,2169,252830373,15
4,RJ115697,히어로,d5bbec0b99c1eeeb30d5a7ab6cdf1afdefe8d04e6d233b...,NaN,0,157342835,174825369,74.25,373.0,232.75,...,6,7,5.0,6.0,90,277.5,7132,1982,208317181,12

In [24]:
df.columns

Index(['character_name', 'character_class', 'ocid', 'date', 'remain_ap',
       '최소 스탯공격력', '최대 스탯공격력', '데미지', '보스 몬스터 데미지', '최종 데미지', '방어율 무시',
       '크리티컬 확률', '크리티컬 데미지', '상태이상 내성', '스탠스', '방어력', '이동속도', '점프력', '스타포스',
       '아케인포스', '어센틱포스', 'STR', 'DEX', 'INT', 'LUK', 'HP', 'MP', 'AP 배분 STR',
       'AP 배분 DEX', 'AP 배분 INT', 'AP 배분 LUK', 'AP 배분 HP', 'AP 배분 MP',
       '아이템 드롭률', '메소 획득량', '버프 지속시간', '공격 속도', '일반 몬스터 데미지',
       '재사용 대기시간 감소 (초)', '재사용 대기시간 감소 (%)', '재사용 대기시간 미적용', '속성 내성 무시',
       '상태이상 추가 데미지', '무기 숙련도', '추가 경험치 획득', '공격력', '마력', '전투력',
       '소환수 지속시간 증가'],
      dtype='str')

In [25]:
cols=['character_name','ocid', 'date', 'remain_ap', 'AP 배분 HP', 'AP 배분 MP','아이템 드롭률', '메소 획득량','추가 경험치 획득']
#'AP 배분 STR','AP 배분 DEX', 'AP 배분 INT', 'AP 배분 LUK'

In [26]:
for col in cols:
    df = df.drop([col], axis=1)

In [27]:
df.head()

,character_class,최소 스탯공격력,최대 스탯공격력,데미지,보스 몬스터 데미지,최종 데미지,방어율 무시,크리티컬 확률,크리티컬 데미지,상태이상 내성,...,재사용 대기시간 감소 (초),재사용 대기시간 감소 (%),재사용 대기시간 미적용,속성 내성 무시,상태이상 추가 데미지,무기 숙련도,공격력,마력,전투력,소환수 지속시간 증가
0,메카닉,153868860,181022186,117.00,433.0,56.20,95.49,68,99.20,76,...,5,6,0,5.0,14.0,85,9282,2238,483009339,20
1,섀도어,94223427,104692695,105.50,281.0,72.46,88.26,95,96.15,75,...,0,6,7,5.0,6.0,90,7841,1956,177511333,0
2,키네시스,104335257,112188445,106.00,293.0,173.09,94.07,109,123.00,71,...,5,6,15,5.0,9.0,93,1959,6728,145531692,0
3,은월,253387095,281541213,183.00,289.0,104.16,93.95,100,164.00,95,...,3,6,7,5.0,9.0,90,9535,2169,252830373,15
4,히어로,157342835,174825369,74.25,373.0,232.75,91.54,92,94.35,77,...,2,6,7,5.0,6.0,90,7132,1982,208317181,12

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 40 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   character_class  70 non-null     str
 1   최소 스탯공격력         70 non-null     int64
 2   최대 스탯공격력         70 non-null     int64
 3   데미지              70 non-null     float64
 4   보스 몬스터 데미지       70 non-null     float64
 5   최종 데미지           70 non-null     float64
 6   방어율 무시           70 non-null     float64
 7   크리티컬 확률          70 non-null     int64
 8   크리티컬 데미지         70 non-null     float64
 9   상태이상 내성          70 non-null     int64
 10  스탠스              70 non-null     int64
 11  방어력              70 non-null     int64
 12  이동속도             70 non-null     int64
 13  점프력              70 non-null     int64
 14  스타포스             70 non-null     int64
 15  아케인포스            70 non-null     int64
 16  어센틱포스            70 non-null     int64
 17  STR              70 non-null     int64
 18  DEX              70 non-null     int64
 19  INT              70 non-null     int64
 20  LUK              70 non-null     int64
 21  HP               70 non-null     int64
 22  MP               67 non-null     float64
 23  AP 배분 STR        70 non-null     int64
 24  AP 배분 DEX        70 non-null     int64
 25  AP 배분 INT        70 non-null     int64
 26  AP 배분 LUK        70 non-null     int64
 27  버프 지속시간          70 non-null     int64
 28  공격 속도            70 non-null     int64
 29  일반 몬스터 데미지       70 non-null     float64
 30  재사용 대기시간 감소 (초)  70 non-null     int64
 31  재사용 대기시간 감소 (%)  70 non-null     int64
 32  재사용 대기시간 미적용     70 non-null     int64
 33  속성 내성 무시         70 non-null     float64
 34  상태이상 추가 데미지      70 non-null     float64
 35  무기 숙련도           70 non-null     int64
 36  공격력              70 non-null     int64
 37  마력               70 non-null     int64
 38  전투력              70 non-null     int64
 39  소환수 지속시간 증가      70 non-null     int64
dtypes: float64(9), int64(30), str(1)
memory usage: 22.7 KB

In [29]:
df['character_class']=df['character_class'].astype('category')

In [30]:
y = df['전투력'] # target data
X= df.drop(['전투력'], axis=1) #feature data

In [31]:
from sklearn.model_selection import train_test_split
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.25, random_state=0)
print(f'X_tr.shape: {X_tr.shape}')

X_tr.shape: (52, 39)

In [34]:
from xgboost import XGBRegressor, plot_importance
hp = {
    "random_state" : 42,
    "max_depth" : 2,
    "n_estimators" : 100, # 수행할 부스팅 단계 수
    "verbose" : 0 # 부스팅 단계 출력 안보이게 하기ㅗㅖㅒ
}

# Get the list of categorical features


XGB = XGBRegressor(**hp,enable_categorical=True).fit(X_tr, y_tr)
print(f'훈련용 평가지표: {XGB.score(X_tr, y_tr)}'),print(f'평가용 평가지표: {XGB.score(X_te, y_te)}')

훈련용 평가지표: 0.9999995827674866
평가용 평가지표: 0.6542540788650513

c:\Dev\project\SKN27-3rd-1TEAM\.venv\Lib\site-packages\xgboost\training.py:183: UserWarning: [20:30:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "verbose" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

(None, None)