In [2]:
import pandas as pd

In [5]:
df=pd.read_csv('genesis_weapon_liberation.csv')

In [6]:
df.head()

,sample_index,character_name,ocid,world_name,level,job,union_level,combat_power,boss_damage_pct,ignore_defense_pct,critical_damage_pct,final_damage_pct,starforce,arcane_force,liberation_quest_clear,genesis_weapon_liberated,source
0,1,윤봄,f3d2ca03a923e574b670fcdd58d14f67,베라,295,비숍,9959.0,326534624,504.0,96.82,115.40,233.49,256.0,1360.0,2,1,existing_nexon_open_api_collection
1,2,세속,a5ac778c63af8e46801d8a4a0805f78a,베라,299,호영,10333.0,243071229,354.0,93.36,127.30,102.60,311.0,1380.0,1,1,existing_nexon_open_api_collection
2,3,덥죠,793ba4700bdb2defc00210be4319cb25,베라,298,히어로,9147.0,159219516,422.0,92.04,105.40,247.88,335.0,1360.0,1,1,existing_nexon_open_api_collection
3,4,구보,a713b32b9a2359def64d0b6e664b7e8a,루나,297,아크,10304.0,376230113,385.0,95.83,160.15,55.23,268.0,1370.0,2,1,existing_nexon_open_api_collection
4,5,Given,6203dcc16036377b9e5d9661403f8419efe8d04e6d233b...,루나,297,아델,10806.0,233158433,301.0,93.56,115.75,96.58,327.0,1350.0,2,1,existing_nexon_open_api_collection

In [7]:
df.columns

Index(['sample_index', 'character_name', 'ocid', 'world_name', 'level', 'job',
       'union_level', 'combat_power', 'boss_damage_pct', 'ignore_defense_pct',
       'critical_damage_pct', 'final_damage_pct', 'starforce', 'arcane_force',
       'liberation_quest_clear', 'genesis_weapon_liberated', 'source'],
      dtype='str')

In [8]:
cols=['sample_index', 'character_name', 'ocid', 'liberation_quest_clear','source',]
#'AP 배분 STR','AP 배분 DEX', 'AP 배분 INT', 'AP 배분 LUK'

In [9]:
for col in cols:
    df = df.drop([col], axis=1)

In [10]:
df.head()

,world_name,level,job,union_level,combat_power,boss_damage_pct,ignore_defense_pct,critical_damage_pct,final_damage_pct,starforce,arcane_force,genesis_weapon_liberated
0,베라,295,비숍,9959.0,326534624,504.0,96.82,115.40,233.49,256.0,1360.0,1
1,베라,299,호영,10333.0,243071229,354.0,93.36,127.30,102.60,311.0,1380.0,1
2,베라,298,히어로,9147.0,159219516,422.0,92.04,105.40,247.88,335.0,1360.0,1
3,루나,297,아크,10304.0,376230113,385.0,95.83,160.15,55.23,268.0,1370.0,1
4,루나,297,아델,10806.0,233158433,301.0,93.56,115.75,96.58,327.0,1350.0,1

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   world_name                249 non-null    str
 1   level                     249 non-null    int64
 2   job                       249 non-null    str
 3   union_level               243 non-null    float64
 4   combat_power              249 non-null    int64
 5   boss_damage_pct           249 non-null    float64
 6   ignore_defense_pct        249 non-null    float64
 7   critical_damage_pct       249 non-null    float64
 8   final_damage_pct          249 non-null    float64
 9   starforce                 249 non-null    float64
 10  arcane_force              249 non-null    float64
 11  genesis_weapon_liberated  249 non-null    int64
dtypes: float64(7), int64(3), str(2)
memory usage: 28.4 KB

In [12]:
df['world_name']=df['world_name'].astype('category')
df['job']=df['job'].astype('category')

In [13]:
y = df['genesis_weapon_liberated'] # target data
X= df.drop(['genesis_weapon_liberated'], axis=1) #feature data

In [14]:
from sklearn.model_selection import train_test_split
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.25, random_state=0)
print(f'X_tr.shape: {X_tr.shape}')

X_tr.shape: (186, 11)

In [16]:
from xgboost import XGBRegressor, plot_importance
hp = {
    "random_state" : 42,
    "max_depth" : 2,
    "n_estimators" : 100, # 수행할 부스팅 단계 수
    "verbose" : 0 # 부스팅 단계 출력 안보이게 하기ㅗㅖㅒ
}

# Get the list of categorical features


XGB = XGBRegressor(**hp,enable_categorical=True).fit(X_tr, y_tr)
print(f'훈련용 평가지표: {XGB.score(X_tr, y_tr)}'),print(f'평가용 평가지표: {XGB.score(X_te, y_te)}')

훈련용 평가지표: 0.9999756217002869
평가용 평가지표: 0.8824384212493896

c:\Dev\project\SKN27-3rd-1TEAM\.venv\Lib\site-packages\xgboost\training.py:183: UserWarning: [00:10:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "verbose" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

(None, None)